---
title: Linguistic autobiography
author: Stefano Coretta
date: '2021-04-29'
slug: linguistic-autobio
categories:
  - Bio
tags:
  - language
  - linguistic-autobiography
---

I was born in Verbania, a town sitting on the coast of Lake Maggiore in Northen Italy.
Both my mother and my father were born in Verbania.
My father's family is from Verbania too, although I don't know much about the family's past, and can only tell that my paternal grandparents were also born in Verbania.
On the other hand, my mother's family is originally from two small villages of the province of Reggio Calabria, in Southern Italy.

Both my parents speak Italian, or more specifically the "regional" Italian of the area.
My father grew up speaking Italian and Lombard, another Romance glossolect of Northern Italy, in a Lombard-speaking enviroment, although Italian is (at least now) his dominant language.
He basically never spoke Lombard to me, but a few exceptions involving the one odd sentence.
My mother grew up speaking Italian and sometimes Calabrese, a Romance glossolect of Southern Italy.
She has always spoken to me in Italian, which is her dominant language.
My maternal grandparents, whith whom I spent most of my childhood, were born in the province of Reggio Calabria, and spoke Calabrese as their first and dominant language.
They also spoke the regional Italian of that province, which as far as I remember didn't change much after they moved to Verbania in the late 50s early 60s.
While spending time with my grandparents as a young child, I would listen to them speaking Calabrese with each other, and they would at times speak in Calabrese to me, although they spoke Southern regional Italian to me most of the time.

Granddad:
    Minica, viri chi vaju nta Beneti mi pigghiu u latti ca finiu. Mi portu a Stefano, ca ci facimu na passiata.

It: Domenica, guarda che vado alla Bennet a prendere il latte ch'è finito. Mi porto dietro Stefano, che ci facciamo una passeggiata.

Grandma:
    Va bonu, iati iati, pigghia puru cincu pesriche i u zuccuru ca vogghiu fari a marmellata.

It: Va bene, andate andate, prendi pure cinque pesche e lo zucchero che voglio fare la marmellata.

Being immersed in a Calabrese-speaking enviroment, I developed a certain level of passive knowledge of it.
I can follow along conversations in Calabrese but I would not really be able to interact using it.


