project:
  type: website
  execute-dir: project
  output-dir: docs
  resources:
    - img

website:
  title: "Stefano Coretta"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
      - href: teaching.qmd
        text: Teaching
      - href: meta.qmd
        text: Meta
      - href: blog.qmd
        text: Blog

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

bibliography: /Users/ste/texmf/bibtex/bib/linguistics.bib
csl: /Users/ste/.local/share/pandoc/csl/unified-style-sheet-for-linguistics.csl

execute: 
  echo: false
  freeze: auto

knitr:
  opts_chunk: 
    message: false