project:
  type: website
  execute-dir: project
  output-dir: docs
  resources:
    - img
    - files
    - data
    - .nokejyll

website:
  title: "Stefano Coretta"
  favicon: img/favicon.png
  site-url: https://stefanocoretta.github.io
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
      - href: teaching.qmd
        text: Teaching
      - href: meta.qmd
        text: Meta
      - href: output/index.qmd
        text: Output
      - href: blog.qmd
        text: Blog
      - href: files/CorettaCV.pdf
        text: CV

format:
  html:
    theme: [flatly, custom.scss]
    css: styles.css
    toc: true
    bibliography: references.bib
    csl: unified-style-sheet-for-linguistics.csl

execute: 
  echo: false
  freeze: auto

knitr:
  opts_chunk: 
    message: false

callout-icon: false