theme = "hugo-PaperMod"
baseURL = "https://stefanocoretta.github.io"
languageCode = "en-gb"
title = "Stefano Coretta"
publishDir = "docs"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$", "(^|/)renv$", "renv\\.lock$"]

[markup.goldmark.renderer]
unsafe = true

[Params]
  ShowReadingTime = "true"

[params]

  [params.homeInfoParams]
  Title = "s"
  Description = "s"

[[menu.main]]
name = "Home"
url = ""
weight = -40

[[menu.main]]
name = "Research"
url = "research/"
weight = -30

[[menu.main]]
name = "Teaching"
url = "teaching/"
weight = -29

[[menu.main]]
name = "Meta"
url = "meta/"
weight = -25

[[menu.main]]
name = "Output"
url = "output/"
weight = -20

[[menu.main]]
name = "Blog"
url = "archives/"
weight = -10

[[menu.main]]
name = "CV"
url = "docs/CorettaCV.pdf"
weight = 0
