theme = "hugo-PaperMod"
baseURL = "https://stefanocoretta.github.io"
languageCode = "en-gb"
title = "Stefano Coretta"

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_cache$", "\\.knit\\.md$", "\\.utf8\\.md$"]

[params]

  [params.homeInfoParams]
  Title = "s"
  Description = "s"

[[menu.main]]
name = "Research"
url = "research/"

[[menu.main]]
name = "Blog"
url = "archives/"
