---
title: Researcher's orientation
number-sections: true
bibliography: references.bib
---

In the following sections, you can find my [researcher's orientation]{.smallcaps}.

::: callout-note
## Researcher's orientation

The researcher's orientation is the combination of every aspect specific to an individual researcher that shape how the researcher approaches and practises research.

This includes, but it is not limited to, lived experiences, social positionality, philosophical stance, personal beliefs, methodological theory, and more.
:::

This is a work in progress, in two senses:

-   In one sense, it is not exhaustive and I will be adding content as it occurs to me.
-   In the other sense, it is an ever-changing document, since I will frequently change my mind about any part(s) of content herein.

# Positionality

Positionality statements are about a reflexive understanding of one's own world view and how it affects one’s own research [@darwinholmes2020; @goundar2025; @jafar2018; @lazard2020; @tomlinson2023].
There isn't a single accepted way of writing a positionality statement nor what should be covered in them.
I personally take a positionality statement to be the social position of the researcher in the research landscape.

I identify as a neurodiverse male academic of Mediterranean ethnicity.
I was born and raised in Northern Italy, but I have been living in the United Kingdom for a decade and I think of this country as my home.
Most of my current research is about research methods and how research practices shape linguistic research.
In this sense, I have an in-group point of view, being myself a researcher.

# Philosophical stance

My philosophical stance is a syncretic integration of non-dual monism, anti-realism, holism, cosmopsychism, spiritualism, subjective Bayesian epistemology, and ecological awareness.

Ontologically, this framework entails an ultimate monistic reality that transcends Cartesian dualism (mental/physical plane), so that anti-realism is understood as rejecting the metaphysical framing of a strict mind-independent vs mind-dependent divide.
Mind, consciousness, experience, and the cosmos are understood as manifestations of a single non-dual ultimate reality.
Furthermore, cosmopsychism entails that the entire cosmos has a fundamental experiential aspect and that all entities have experience deriving from the cosmic experience.
Holism, the idea of a unified whole which is more than the sum of its parts, is another central aspect of Stefano's philosophical stance, and it is intended as applied to ontology (reality is whole), epistemology (knowledge is relational) and methodological (description and explanation requires whole-level analyses).

Bayesian epistemology, which I use in my research and teach in my courses, is grounded on belief updating under uncertainty and inference given priors representing belief and evidence.
Under this stance, quantitative methods are viewed and practised not in a reductionist way (explaining phenomena based entirely on lower-level terms) but simply as representing phenomena numerically as one way of operationalise entities, events and relations.

# Methodological theory

From the point of view of methodological theory and practice, I am an active advocate of Open Research practices for a more transparent, well-grounded and reflexive scholarship.
**Open Research** encompasses "concepts of openness, transparency, rigor, reproducibility, replicability, and accumulation of knowledge" [@cruwell2019] put to the service of "making the content and process of producing evidence and claims transparent and accessible to others" [@munafo2017].[^1]

[^1]: *Open Research* is a more inclusive term than the more common *Open Science* term.

<!-- TODO: slow science -->

I am also a supporter of the **Slow Science** movement, part of the broader "slow" movement (as in "slow-food"), which can be summarised with this quote from the [manifesto](http://slow-science.org): "We do need time to think. We do need time to digest. We do need time to misunderstand each other".

<!-- TODO: ethics -->

<!-- TODO: research project management -->

<!-- TODO: methods as theory, theory = concepts + methods, theory and applications, basic science and applied science -->

<!-- TODO: statistics -->

<!-- TODO: philosophy of science: three books -->

Philosophy and science might seem two very unrelated fields, but in fact **philosophy of science** is an extremely important intersection of the two, with broad implications for research methods, from experiment planning, through statistical modelling, to inference.
I'll expand on this some time in the future, but for now I can strongly recommend the following books:

-   *Philosophy of science: Very short introduction* [@okasha2016].
-   *Understanding psychology as a science: An introduction to scientific and statistical inference* [@dienes2008].
-   *The Systems View of life: A unifying vision* [@capra2018].

## References {.unnumbered}
