# Courses

Check the [Data Analysis \@ UoE LEL](https://uoelel.github.io) website for learning resources on research methods in linguistics.

::: callout-note
## Current

-   **Quantitative Methods for Linguistics and English Language** (UG and PG). [Course website](https://uoelel.github.io/qml/)
:::

::: callout-note
## Previous

-   **Data Analysis for Linguistics and English Language** (undergraduate).
    [Course website](https://uoelel.github.io/qml/)

-   **Statistics and Quantitative Methods** \[[LASC11171](http://www.drps.ed.ac.uk/22-23/dpt/cxlasc11171.htm)\].
    [Course website](https://stefanocoretta.github.io/sqmf/)

-   **Statistics and Quantitative Methods** \[[LASC11172](http://www.drps.ed.ac.uk/22-23/dpt/cxlasc11172.htm)\].
    [Course website](https://stefanocoretta.github.io/sqmb/)

-   **Making a language: Conlanging and Linguistic Typology** (Guided Research in Linguistics and English Language).
    [Course website](https://stefanocoretta.github.io/grs-conlang/)

-   **Research Methods in Developmental Linguistics** \[[LASC11127](http://www.drps.ed.ac.uk/21_22_Archive_at_01-09-2021/dpt/cxlasc11127.htm)\].

-   Individual classes taught in **Introduction to Language Research** \[[LASC11091](http://www.drps.ed.ac.uk/21_22_Archive_at_01-09-2021/dpt/cxlasc11091.htm)\], **Phonetics and Laboratory Phonology** \[[LASC11137](http://www.drps.ed.ac.uk/21_22_Archive_at_01-09-2021/dpt/cxlasc11137.htm)\], **Speech Production and Perception** \[[LASC11138](http://www.drps.ed.ac.uk/21_22_Archive_at_01-09-2021/dpt/cxlasc11138.htm)\].
:::

# Workshops

Here you can find information on workshops I offer.
Adaptations of pre-existing workshops (e.g. shorter/longer version, focus on a specific topic/field) are possible and proposals for new workshops are welcome.
Get in contact with me for queries.

If you are looking for workshops run internally (in the LEL department of UoE), please check the [STeW](https://uoelel.github.io/stew.html) page on the [Data Analysis \@ UoE LEL](https://uoelel.github.io).

## Beginners

::: callout-tip
#### Writing dissertations/theses in Quarto

+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟢 Beginners                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | MS Word is for dinosaurs! 🦕 This workshop introduces you to a modern and flexible writing and publishing system, called [Quarto](https://quarto.org). Writing a dissertation/thesis with Quarto is straightforward when using a Quarto Book project. Quarto uses a simple mark-up language to style your text, [Markdown](https://www.markdownguide.org), and it makes it very easy to handle figures, tables, citations and other scholarly writing features. |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | -   No prior experience with Quarto nor Markdown is required, but you **must install Quarto and a text editor as explained here**: <https://quarto.org/docs/get-started/>.                                                                                                                                                                                                                                                                                      |
|                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                   | -   If you are unfamiliar with the text editors listed on the page, use VS Code (this will be the editor of the workshop, but you can follow along with any other editor). If you use VS Code, you should install the Quarto extension (check online).                                                                                                                                                                                                          |
|                   |                                                                                                                                                                                                                                                                                                                                                                                                                                                                 |
|                   | -   If you wish to try out Zotero for reference managing, you can also install Zotero: <https://www.zotero.org>. (The workshop will not cover how to use Zotero, but you will see how Zotero integrates with Quarto).                                                                                                                                                                                                                                           |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/diss-quarto/>                                                                                                                                                                                                                                                                                                                                                                                                                 |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Watch](https://media.ed.ac.uk/media/Writing+dissertations+theses+in+Quarto/1_x8gdl8o3/308657412)                                                                                                                                                                                                                                                                                                                                                               |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-tip
#### Data Version Control for Researchers

+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟢 Beginners                                                                                                                                                                                                                                                                                                            |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | A fundamental aspect of Open Research is ensuring the reproducibility of data processing and analyses. Part of this endeavour is concerned with data versioning and backup. Many researchers have now become familiar with versioning systems like git, popularised by the GitHub online platform.                      |
|                   |                                                                                                                                                                                                                                                                                                                         |
|                   | This workshop will introduce participants to the Data Version Control software ([DVC](https://%20dvc.org)), specifically designed to work efficiently with non-textual data types. DVC works in unison with git, so that git users can simply add it to their existing workflow and integrate code and data versioning. |
|                   |                                                                                                                                                                                                                                                                                                                         |
|                   | After a brief conceptual introduction to version control, git and DVC, participants are guided through a hands-on tutorial which teaches them the basics of git and DVC versioning using a toy project.                                                                                                                 |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Only basic familiarity with file management and command line is required (<https://tutorial.djangogirls.org/en/intro_to_command_line/>).                                                                                                                                                                                |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | [https://github.com/stefanocoretta/dvc-res](http://127.0.0.1:32869/#0 "https://github.com/stefanocoretta/dvc-res")                                                                                                                                                                                                      |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-tip
#### Introduction to (Xe)LaTeX

+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟢 Beginners                                                                                                                                                                             |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | XeLaTex is is a mark-up language for text editing and typesetting (and more). It's a dialect of the LaTeX format that introduces full Unicode support and handling of TTF and OTF fonts. |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | None.                                                                                                                                                                                    |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | [https://github.com/stefanocoretta/xelatex-workshop](http://127.0.0.1:32869/#0 "https://github.com/stefanocoretta/xelatex-workshop")                                                     |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-tip
#### Open Research practices in linguistics

+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟢 Beginners                                                                                                                                                                             |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | A primer for Open Research practices in linguistics for all researchers/scholars. This workshop will cover practices that can be applied to qualitative and quantitative research alike. |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | None.                                                                                                                                                                                    |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/open-research/>                                                                                                                                        |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Watch](https://media.ed.ac.uk/media/Open+Research+practices+for+linguistics/1_r2ansvf0)                                                                                                 |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-tip
#### intRo: Data visualisation with R

+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟢 Beginners                                                                                                                                 |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | This is an introduction to R and data visualisation for absolute beginners. If you want to learn R for the first time, this is a good start. |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | None.                                                                                                                                        |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://intro-rstats.github.io>                                                                                                             |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Day 1](https://media.ed.ac.uk/media/intRoA+Day+1/1_aah5ninw), [Day 2](https://media.ed.ac.uk/media/intRoA+Day+2/1_196jx1qj)                 |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-tip
#### Mindless statistics and the "null ritual"

+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟢🟠🔴 Any level                                                                                                                                                                                                                                                                                                                                                                                                                |
+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | In this workshop we will go through bad statistical practices that are common even among experienced researchers and how to avoid them. In particular, we will talk about the "null ritual", which is a invalid approach to frequentist statistics commonly used in research. Most of the content of the workshop will be drawn from Gigerenzer's [Mindless Statistics](https://www.doi.org/10.1016/j.socec.2004.09.033) paper. |
+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Some familiarity with frequentist statistics is useful but not necessary. This workshop is thought for both beginners and experienced researchers or students, whether they normally use quantitative, qualitative or mixed methods.                                                                                                                                                                                            |
+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/null-ritual/>                                                                                                                                                                                                                                                                                                                                                                                 |
+-------------------+---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-tip
#### `basicBayes`: Learn Bayesian Linear Models for Beginners

+-------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟢 Beginners                                                                                                                           |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | This workshop introduces Bayesian linear models in R to participants without previous knowledge of linear models (but knowledge of R). |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | None.                                                                                                                                  |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | [https://stefanocoretta.github.io/basicBayes/](http://127.0.0.1:32869/#0 "https://stefanocoretta.github.io/basicBayes/")               |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------+
:::

## Intermediate

::: callout-warning
#### `learnBayes`: Introduction to Bayesian Regression Models

+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟠 Intermediate                                                                                                                                                                                                                                |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | This workshop is an introduction to Bayesian regression models using the brms packages.                                                                                                                                                        |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | This workshop assumes you have a solid command of R and tidyverse packages, and familiarity with regression modelling (including interpreting coefficients and interactions).                                                                  |
|                   |                                                                                                                                                                                                                                                |
|                   | If you wish to revise any of these topics, we recommend the following resources:                                                                                                                                                               |
|                   |                                                                                                                                                                                                                                                |
|                   | -   [R for Data Science](https://r4ds.had.co.nz/) (online book).                                                                                                                                                                               |
|                   |                                                                                                                                                                                                                                                |
|                   | -   [Statistics for Linguists in R](https://www.routledge.com/Statistics-for-Linguists-An-Introduction-Using-R/Winter/p/book/9781138056091) (textbook).                                                                                        |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/learnBayes/>                                                                                                                                                                                                 |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | You can watch an earlier version of this workshop (note that the slides in the recording don't closely match those currently available on the website): [Watch](https://media.ed.ac.uk/media/LEL+Bayesian+Linear+Models+2023+Sem+1/1_slt88gj6) |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-warning
#### Including random effects in Bayesian Linear models with `brm()`

+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟠 Intermediate                                                                                                                          |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | This workshop is targeted especially to **MSc students** who have attended the **QML course**.                                           |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Anybody who has attended the previous Bayesian workshops or who has experience with basic linear models with `brm()` is welcome to join. |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://uoelel.github.io/brm-group/>                                                                                                    |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Watch](https://media.ed.ac.uk/media/STeW+-+Including+random+effects+in+Bayesian+Linear+models+with+brm%28%29/1_5tz3sfdl)                |
+-------------------+------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-warning
#### `learnGAM`: Generalised Additive Mixed Models (GAMMs)

+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟠 Intermediate                                                                                                                            |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | GAMMs are useful to analyse historical data, time-series data or data that could have non-linear effects (like language development data). |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | It assumes some familiarity with linear models fitted with `lmer()`/`glmer()` or `brm()`.                                                  |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/learnGAM/>                                                                                               |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Watch](https://media.ed.ac.uk/media/learnGAMA+GAMMs+workshop+for+LEL+%282023%29/1_qsbcwusm) (recording of previous run of the workshop)   |
+-------------------+--------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-warning
#### `proPower`: Prospective power analyses for frequentist regression models

+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟠 Intermediate                                                                                                                                                                                                                                                                                                                                                                                                                              |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | You will learn how to perform prospective power analyses for regression/linear models fitted with the frequentist lme4 package. Power analyses are a necessary (albeit always neglected) component of frequentist analyses, since they help the researcher determine the required sample size. Much of the replicability crisis we are facing is due to lack of statistical power (aka low sample sizes) in virtually all published studies. |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Need to be familiar with regression/linear models in R including models with random effects and binomial/Bernoulli (aka logistic) regressions.                                                                                                                                                                                                                                                                                               |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/proPower/>                                                                                                                                                                                                                                                                                                                                                                                                 |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Watch](https://media.ed.ac.uk/media/proPower%3A+Prospective+power+analyses+for+frequentist+regression+models/1_bgsbzz7a)                                                                                                                                                                                                                                                                                                                    |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-warning
#### `learnB4SS`: Learn Bayesian Analysis for Speech Sciences

+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🟠 Intermediate                                                                                                                                                                                                                                                                                                                         |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | Together with Timo Roettger and Joseph V. Casillas, we introduce the logic of Bayesian inference and compare it to Null Hypothesis Significance Testing (NHST). After providing a brief conceptual introduction, the course walks through a Bayesian statistical analysis using R [@rcoreteam2020] and the package brms [@burkner2018]. |
|                   |                                                                                                                                                                                                                                                                                                                                         |
|                   | We explain how to set up a Bayesian regression model (including setting appropriate priors), how to interpret the results, how to diagnose model convergence, and how to visualize and report the results. In hands-on exercises, the participants immediately apply their knowledge to a speech data set in R.                         |
|                   |                                                                                                                                                                                                                                                                                                                                         |
|                   | Check out the [workshop website](https://learnb4ss.github.io) for more info.                                                                                                                                                                                                                                                            |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Need to be familiar with regression/linear models in R including models with random effects and binomial/Bernoulli (aka logistic) regressions.                                                                                                                                                                                          |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://learnb4ss.github.io/learnB4SS/>                                                                                                                                                                                                                                                                                                |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Watch](https://www.youtube.com/@learnb4ss313/playlists)                                                                                                                                                                                                                                                                                |
+-------------------+-----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

## Advanced

::: callout-important
#### Ordinal models for Likert/rating-scale data

+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🔴 Advanced                                                                                                                                                                                                                                                                                     |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Description**   | In this workshop you will learn how to model data from Likert/rating scales, such as the ones commonly used in developmental and psycho- linguistics using ordinal models.                                                                                                                      |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Need to be familiar with regression/linear models in R including models with random effects and binomial/Bernoulli (aka logistic) regressions. While a background in Bayesian inference is useful, the workshop will explain the basics of Bayesian inference in the context of ordinal models. |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/learnOrd/>                                                                                                                                                                                                                                                    |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | [Watch](https://media.ed.ac.uk/media/learnOrd%3A+Ordinal+regression+models+for+Likert+rating+scales+data/1_im4onksw/308657412)                                                                                                                                                                  |
+-------------------+-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

::: callout-important
#### Bayesian Priors in Linear Models

+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Level**         | 🔴 Advanced                                                                                                                                                                                                                                                          |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Prerequisites** | Need to be familiar with Bayesian Linear Models including Random Effects and/or have attended the *Introduction to Bayesian Linear Models* workshop. This is **not** suitable for students who have only attended the QML course (see below for dedicated workshop). |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Materials**     | <https://stefanocoretta.github.io/learnBayes/> (Session 2)                                                                                                                                                                                                           |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
| **Recording**     | Unfortunately I forgot to record this, but you can watch the following videos from the [learnB4SS](https://learnb4ss.github.io) to learn about priors (these videos go into much more detail!).                                                                      |
|                   |                                                                                                                                                                                                                                                                      |
|                   | -   [learnB4SS — 03 Application to Regression II: Priors and Bayesian Updating (Part I)](https://media.ed.ac.uk/media/learnB4SS+%E2%80%94+03+Application+to+Regression+IIA+Priors+and+Bayesian+Updating+%28Part+I%29/1_vl395dhg)                                     |
|                   |                                                                                                                                                                                                                                                                      |
|                   | -   [learnB4SS — 03 Application to Regression II: Priors and Bayesian Updating (Part II)](https://media.ed.ac.uk/media/learnB4SS+%E2%80%94+03+Application+to+Regression+IIA+Priors+and+Bayesian+Updating+%28Part+II%29/1_6e35jw34)                                   |
+-------------------+----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------+
:::

### References
