---
title: Short review of phonological databases
author: Stefano Coretta
date: 2014-06-30
type: post
categories:
  - Phonetology
tags:
  - databases
  - distinctive features
  - linguistics
  - phonetics
  - phonology
  - statistics
  - computational linguistics
summary: "A review of available phonological databases (2014)."
---

List of available phonological databases (updated 2019-03-22):

  * UCLA Phonological Segment Inventory Database ([UPSID][1])
  * Lyon-Albuquerque Phonological Systems Database ([LAPSyD][2])
  * Phonetics Information Base and Lexicon ([PHOIBLE][3])
  * World Atlas of Language Structures ([WALS][6])
  * South American Phonological Inventory Database ([SAPhon][4])
  * BDPROTO Proto-language segment inventories ([DBPROTO][7])
  * Database of Eurasian phonological inventories ([link][8])
  * Indo-European Phonological Inventory Database ([IEPhon][5], dead link)

# [UCLA Phonological Segment Inventory Database][1]

  * **number of records**: 451 languages
  * **type of sample**: genetically balanced
  * **interface**: desktop and web
  * **data**: inventory, language family, comments, source
  * **searchable**: for language, number of sounds, frequency index, family and phonetic features
  * **search display**: list

# [Lyon-Albuquerque Phonological Systems Database][2]

  * **number of records**: (in progress)
  * **type of sample**: not balanced
  * **interface**: web
  * **data**: consonant and vowel inventories, syllable structure, stress and tone systems, language location and classification
  * **searchable**: for language (name, iso, classification), sounds (table format), phonetic features, syllable
  * **search display**: segment table, boolean (sound, feature, area, family, syllable)

# [Phonetics Information Base and Lexicon][3]

  * **number of records**: 1,010 languages
  * **type of sample**: not balanced
  * **interface**: web
  * **data**: inventory, segment class, language location
  * **searchable**: for language (name, iso), sounds (list format), source
  * **search display**: list

# [World Atlas of Language Structures][6]

  * **number of records**: 2,679 languages
  * **type of sample**: balanced
  * **interface**: desktop and web
  * **data**: size of consonant inventory, size of vowel inventory, consonant-vowel ratio, voicing and gaps in plosive system, uvular consonant, glottalized consonants, velar nasal, reduplication
  * **searchable**: for language (name, iso, genus, family, macroarea; list format),  characteristics (list format)
  * **search display**: list and map

# [South American Phonological Inventory Database][4]

  * **number of records**:  359 languages
  * **type of sample**: not balanced, South America
  * **interface**: web
  * **data**: segment inventory, suprasegmentals, language (name, iso, family, country)
  * **searchable**: for language (name, iso, family, country; list format and map),  sounds (table)
  * **search display**: table, list and map

# [BDPROTO Proto-language segment inventories][7]

  * **number of records**:  137 languages
  * **type of sample**: genialogical diversity, convenience sample
  * **interface**: offline (csv, sql)
  * **data**: segment inventory, suprasegmentals, language (name, iso, family, homeland, time depth)
  * **searchable**: yes
  * **search display**: none

# [Database of Eurasian phonological inventories][8]

  * **number of records**:  416 languages
  * **type of sample**: 
  * **interface**: web and offline (json)
  * **data**: segment inventory, suprasegmentals, language (name, family, group)
  * **searchable**: segment inventory, language, location
  * **search display**: map, list, segments table

# [Indo-European Phonological Inventory Database][5] [dead link]

  * **number of records**:  18 languages
  * **type of sample**: not balanced, Indo-European family
  * **interface**: web
  * **data**: segment inventory, language (name, family, area)
  * **searchable**: for language (name, family, country; list format and map),  sounds (table)
  * **search display**: table, list and map

 [1]: http://web.phonetik.uni-frankfurt.de/upsid.html
 [2]: http://www.lapsyd.ddl.ish-lyon.cnrs.fr
 [3]: http://phoible.org
 [4]: http://linguistics.berkeley.edu/~saphon/en/
 [5]: https://studiumanistici.unipv.it/?pagina=p&id=494
 [6]: http://wals.info
 [7]: https://github.com/bdproto/bdproto
 [8]: http://eurasianphonology.info
