---
title: My researcher's positionality statement
author: Stefano Coretta
date: '2021-04-29'
slug: positionality
categories:
  - Meta-models
tags:
  - positionality
  - meta-science
bibliography: /Users/ste/texmf/bibtex/bib/linguistics.bib
csl: unified-style-sheet-for-linguistics.csl
output:
  blogdown::html_page:
    number_sections: true
---

# Overview

This is my researcher's [positionality statement]{.smallcaps} [for context, see @darwin2020; @jafar2018].

> The term [positionality]{.smallcaps} both describes an individual's [world view]{.smallcaps} and the [position]{.smallcaps} they adopt about a research task and its social and political context. The individual's world view or 'where the researcher is coming from' concerns [ontological assumptions]{.smallcaps} (an individual's beliefs about the nature of social reality and what is knowable about the world), [epistemological assumptions]{.smallcaps} (an individual's beliefs about the nature of knowledge) and assumptions about [human nature and agency]{.smallcaps} (individual's assumptions about the way we interact with our environment and relate to it).
>
> It is important for new researchers to note here that their positionality not only shapes their work but influences their interpretation, understanding, and, ultimately, their belief in the truthfulness and validity of other's research that they read or are exposed to.

— @darwin2020, p. 1-3.

This is a work in progress, in two senses:

- In one sense, it is not exhaustive and I will be adding content as it occurs to me.
- In the other sense, it is an ever-changing document, since I will frequently change my mind about any part(s) of content herein.

The following sections provide a thought-out description of my ontological and epistemological belief systems.
The reader should interpret all of the statements made here as "my personal opinion".
In some cases *opinion* refers to my [expert opinion]{.smallcaps}, in others to my [intuitions]{.smallcap}.^[For the use of intuition in science, see the work by physicist [Fritjof Capra](https://www.fritjofcapra.net).]
With time, I will add references where/if relevant.

## Ontological

1. [linguisticality]{.smallcaps} is the human ability to communicate through a language, and a [language]{.smallcaps} is a specific communicative system used by a specific group of humans [@haspelmath2020].
1. If one defines [linguisticality]{.smallcaps} as the human ability to communicate through a language, then saying that only humans have linguisticality is a tautology.
1. All living beings are capable of communicating [even plants and fungi, @mancuso2015].

## Epistemological

1. There is no agreement as to what [science]{.smallcaps} actually is.
1. Science is not the only way to gain knowledge.
1. Science has both [objective]{.smallcaps} and [subjective]{.smallcaps} components.
1. Statistics and statistical inference have both [objective]{.smallcaps} and [subjective]{.smallcaps} components [@gelman2017].
1. There is no agreement as to what [language]{.smallcaps}, [human language]{.smallcaps}, [linguistic capacity]{.smallcaps}, [linguisticality]{.smallcaps} actually are.
1. There is no agreement as to whether [language]{.smallcaps}, [human language]{.smallcaps}, [linguistic capacity]{.smallcaps}, [linguisticality]{.smallcaps} are the same thing or if they in principle refer to different entities.
1. There is no agreement as to which components of the human ability to communicate through a language are [innate]{.smallcaps} and which are [learned]{.smallcaps}.
1. There is no agreement as to what [innate]{.smallcaps} actually means.
1. There is no agreement as to whether the human ability to communicate through a language is entirely [domain-specific]{.smallcaps} or entirely [domain-general]{.smallcaps}, or if it is a bit of both.
    1. If it is a bit of both, there is no agreement as to which components are [domain-specific]{.smallcaps} and which are [domain-general]{.smallcaps}.
1. There is no agreement as to what a [language]{.smallcaps} is. In fact, in English *language* is used at times to mean either the human ability/capacity to communicate with a language or to mean a specific language (sometimes written *Language* and *language* respectively).

### References



