---
title: On random effects
author: Stefano Coretta
date: '2021-03-15'
slug: []
categories:
  - Methods
tags:
  - statistics
  - rstats
math: true
---

If you use **mixed-effects models** (aka multilevel models, hierarchical models), I am sure that at some point you asked yourself the following question at least once: *Should I include this variable as a fixed or as a random effect?*

Regrettably, there is no straightforward answer (disappointed, uh?).

The main reason for a lack of a simple heuristic is that, in fact, there are many possible (and most times exclusive) definitions of what a random (vs fixed) effect is.
So to be able to answer our question, we would first have to pick one particular definition.

In the following summary---which paraphrases and takes inspiration from Gelman's [post](https://statmodeling.stat.columbia.edu/2005/01/25/why_i_dont_use/) (and related [journal article](http://www.stat.columbia.edu/~gelman/research/published/banova7.pdf))---I'd like to offer an overview of five main definitions of "random effect" and some thoughts on what mixed-effects modelling entails from a conceptual point of view.

## Five definitions of "random effect"

In his post, Gelman says that there are at least 5 possible ways of defining random effects (with others being subsumable under those 5).
To illustrate these definitions and make them more relatable to phoneticians and phonologists alike, I will make use of a fictitious study of f0 (fundamental frequency) as a correlate of emotional arousal ($\eta$).

Let's assume that we are interested in testing the (made-up) hypothesis that emotional arousal affects the speaker's f0.
We can test this hypothesis using the following model:

$$ f0_{ij} = \alpha + \alpha_j + \beta \times \eta_i $$

where

- $f0_{ij}$ is the outcome variable,
- $\alpha$ is the intercept,
- $\alpha_j$ is the individual speakers' intercept coefficient,
- $\beta$ is the slope,
- and $\eta_i$ is emotional arousal status (`0 = non-aroused`, `1 = aroused`).

This model could be written in R like so:

```{r eval=FALSE}
f0 ~ emo_arousal + (1 | speaker)
```

The following sections discuss the 5 definitions in turn.

### 1. Constant vs varying effects

Fixed effects are constant across individuals, while random effects vary.
For example, in the f0 study, a model with fixed slope $\beta$ and random intercepts $\alpha_j$ corresponds to parallel lines for different speakers j. Kreft and De Leeuw (1998) thus distinguish between fixed and random coefficients.

### 2. Researcher's interest

Effects are fixed if they are interesting in themselves or random if there is interest in the underlying population. In the f0 study, the effect of emotional arousal on f0 is the main focus of interest, while the average f0 of each speaker (A_j) is not relevant. Searle, Casella, and McCulloch (1992, Section 1.4) explore this distinction in depth.

### 3. Sampling

> When a sample exhausts the population, the corresponding variable is fixed; when the sample is a small (i.e., negligible) part of the population the corresponding variable is random.

In our example study, the set of emotional arousal values observed exhausts the "population" of emotional arousal values, while the set of speakers is just a sample from the whole population of speakers (Green and Tukey, 1960).

### 4. Random events

> If an effect is assumed to be a realized value of a random variable, it is called a random effect.

A random variable is a variable generated by a random event. In our f0 study, the speakers that decided to participate to the study are the outcome of random events, while we assume that the relation between f0 and arousal is governed by a specific mathematical relationship (LaMotte, 1983).

### 5. Shrinkage

Fixed effects are estimated using least squares (or, more generally, maximum likelihood) and random effects are estimated with shrinkage ("linear unbiased prediction" in the terminology of Robinson, 1991). This definition is standard in the multilevel modeling literature (see, for example, Snijders and Bosker, 1999, Section 4.2) and in econometrics. Shrinkage refers to the "regression to the mean" effect by which the estimated random effects are attracted towards the estimated mean (intercept). So in the f0 study, the by-speaker random intercepts are "shrunk" towards the estimated fixed intercept. In sum, from a mathematical point of view, fixed effects are effects without shrinkage while random effects are effects with shrinkage. Whether you model an effect with or without shrinkage, doesn't have anything to do with randomness or relevance, but rather it has to do with the underlying process model you expect to have generated the observations you recorded.

## Some thoughts

I personally agree with Gelman's position of avoiding the terms fixed/random altogether, although possibly my favourite definition is number 5, given that it is based on low-level theoretical considerations rather than on practical ones.
In any case, it is always important to think very carefully about what to include as `Y ~ X` and what to include as `Y ~ (1|X)`.

Note that definition (4) makes sense within the frequentist framework of inferential statistics, but less so in the Bayesian framework, given that in the latter everything is a random variable.
Within Bayesian modelling, it is common to use the terms "population-level" effects and "group-level" effects to indicate, respectively, effects that represent a population-wide independent generative process vs the modulation of such a generative process within the population.

Hopefully this helped clarifying what is behind the fixed/random effects dichotomy (rather than making it even more blurry by introducing multiple definitions).
