---
title: On phonologisation
author: Stefano Coretta
date: '2021-04-24'
slug: []
categories:
  - Linguistics
tags:
  - phonology
  - concepts
bibliography: /Users/ste/texmf/bibtex/bib/linguistics.bib
cls: unified-style-sheet-for-linguistics.csl
---

<!-- NOTE: Add that it is a diachronic process -->

After the [post](../2021-03-15-on-random-effects/) on the definition of random effects, I thought about writing another one on the definition of [phonologisation]{.smallcaps}.

As part of my [PhD thesis](https://stefanocoretta.github.io/phd-dissertation/s-ve.html#s:ve-phonologise) on the effect of consonant voicing on vowel duration, I briefly reviewed the five definitions of phonologisation I could find in the literature.
This post includes text from my thesis and expands on a few points.

The main take-away of the sections to follow is that what one means with phonologisation is (unsurprisingly) dependent on the set of assumptions that are part of the framework within which the term is used.
Secondly, these definitions are mutually exclusive, to an extent such that one's argument based on one definition might be inappropriate under another definition.
It is thus important to always contextualise the use of the term when employed, even when the meaning might be self-evident from the context.

## Five definitions of phonologisation

I could identify five different definitions of phonologisation.
These differ substantially, as mentioned above, and are in the most part incompatible with one another.
The five definitions are found within the following general phonological frameworks:

- Structuralism (i.e. classical/traditional phonology).
- Lexical Phonology.
- Stratal Optimality Theory.
- Life-Cycle of Phonological Processes (an extention of Stratal OT).
- Exemplar-based models.

I will discuss each of these in turn.

## Structuralism

The **classical** or **structuralist** definition states that phonologisation occurs when a contextual allophone becomes contrastive, or in other words it becomes a phoneme [@kiparsky2015], generally after the disappearance or replacement of the conditioning context.

A classical example of phonologisation concerns the development of a contrast between velar and palatal consonants from velar consonants in Sanskrit [@hock1991, pp. 149].
At some point in the history of Sanskrit, the velar stops /k/ and /g/ (which derived from PIE velars and labialised velars) where palatalised when followed by /i/ and /e/, creating an allophonic distinction between velars proper and palatal consonants.

The subsequent change of /e/ (and /o/) to /a/ removed the context conditioning palatalisation (the front vowel /e/), thus creating minimal pairs opposing /ka, ga/ and /tʃa, dʒa/.
At this stage, the palatal allophones were phonologised.

| sound change   | phonemic  | phonetic  |
|----------------|-----------|-----------|
|                | /ka, ke/  | [ka, ke]  |
| palatalisation | /ka, ke/  | [ka, tʃe] |
| /e/ > /a/      | /ka, tʃa/ | [ka, tʃa] |

The IE roots for 'what' and 'and' illustrate the phonologisation of the palatal consonants.

- PIE \**kʷod* > Skt. /kad/ *kád* 'what' (cf. Lat. *quod*).
- PIE \*-*kʷe* > Skt. /ke/ [tʃe] > /tʃa/ -*ca* 'and' (cf. Lat. *-que*).

This conceptualisation of phonologisation amounts to saying that phonetic features that were previously computed procedurally (during phonological/phonetic derivation) from an underlying lexical representation are now instead already part of the lexical representation (which is, in structural terms, a string of phonemes).

## Lexical Phonology

Phonologisation assumes a different meaning within the framework of Lexical Phonology [@kiparsky1988].
Lexical Phonology argues that there exist two types of phonological processes: processes that apply at the lexical level (stem and prosodic word), and processes that are post-lexical and apply across the board.^[Note that in generative phonology, of which Lexical Phonology is a strand, speakers are assumed to store abstract, underlying phonemic forms, or representation, in memory. These underlying forms, to be produced, go through a series of neuro-cognitive processes, or derivation, that generate a surface representation which is then sent to the motor system which executes the motor plan corresponding to that surface representation. The details widely vary depending on the model or framework.]
According to the view of Lexical Phonology, a process is phonologised when it goes from being post-lexical to being lexical.

To carry on with the Sanskrit example, palatalisation was initially post-lexical, in other words it was applied across the board during the phonological derivation process after all lexical processes have been applied to the stem and then word.
At some point in the history of Sanskrit, the process of velar palatalisation then started being applied also at the lexical level (with the original "copy" of the process possibly still being applied post-lexically).
Velar palatalisation has been phonologised, creating so called "quasi-phonemes" [i.e. categorical, distinctive units, not yet able to create lexical contrast, @janda1999].

## Stratal Optimality Theory

@kiparsky2000 borrows the definition of phonologisation of Lexical Phonology into Stratal Optimality Theory [@kiparsky2000; @bermudez-otero2017].
Stratal OT assumes that the phonological module of the grammar is divided into three levels (called strata, or domains) as in Lexical Phonology: the stem, the word, and the phrasal level.
OT constraints are independently ordered in each level, so that within each level different orders allow for different outputs to be selected.
Stratal OT also stipulates that phonological constraints apply iteratively (cyclically) from the narrower domain, namely the stem, through the word domain, to the phrasal domain.
Under cyclicity, the output of one domain is passed over as input to the next, and so on.
For @kiparsky2000, phonologisation occurs when the constraint ordering of the phrasal domain (the post-lexical level of Lexical Phonology) is copied over to the word and stem domains (the lexical level of Lexical Phonology).

## Life-Cycle of Phonological Processes

An extension of Stratal OT, the life cycle of phonological processes [@bermudez-otero2007; @bermudez-otero2015], offers yet another definition of phonologisation and a more fine-grained terminological set.
@bermudez-otero2015] reserves the term "phonologisation" for when a physico-physiological (mechanic) phenomenon comes under the control of the speaker/hearer and in fact becomes part of her grammar (more specifically, part of the phonetic module of the grammar).
The process, once it has entered the grammar, can further its "ascent" through increasingly deeper grammatical modules.
A (gradient) phonologised process is said to be "stabilised" (and thus categorical) once it is generated by a categorical phonological rule, which applies at the phrase level.
At this stage, a stabilised process has entered the phonological module of the speaker/hearer.
A stabilised process further undergoes "domain narrowing" when it starts being applied at the word level and then at the stem level.
In the final step in the ascent of a sound pattern through the grammar, a phonological process comes under morphological and lexical control, until "it may die altogether, leaving behind no more than inert traces in underlying representations" [@bermudez-otero2015, pp. 12].

### References
